# See 
# https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
# for ideas.

# Project information
site_name: East Herts Miniature Railway

site_author: "Richard Franks, Tom Martin"
site_description: >-
  Documentation around the East Herts Miniature Railway S&T environment

# Repository
repo_name: EHMRS/emhrs.github.io
repo_url: https://github.com/EHMRS/ehmrs.github.io
edit_uri: edit/main/docs/

site_url: https://ehmrs.github.io/

docs_dir: './docs'

# Copyright
copyright: Copyright &copy; 2016 - 2022 EHMRS

theme:
  # name: "readthedocs"
  name: "material"
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode  # Default values, taken from mkdocs_theme.yml
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: google
  # minify seems advanced. https://squidfunk.github.io/mkdocs-material/customization/#theme-development  
  # - minify:
  #   minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EHMRS
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/EHMRS
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/EHMRS
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ehmrs

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
     anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: 
    - Home: index.md
    - Signalling System Overview: overview.md
    - Signalling Interface Cards: 485card/index.md
    - Devices:
      - Devices: devices/index.md
      - Buttons: devices/buttons.md
      - Frame levers: devices/levers.md
      - Points: devices/points.md
      - Relays: devices/relays.md
      - Track sections: devices/sections.md
      - Sensors: devices/sensors.md
      - Signals: devices/signals.md
  - MQTT:
    - MQTT: mqtt/index.md
    - Topics: mqtt/topics.md
  - Signalling System Core:
    - Signalling System Core: mainsystem/index.md
    - Todo: mainsystem/Pages/todo.md
    - Classes: mainsystem/Classes/index.md
    - Namespaces: mainsystem/Namespaces/index.md
  - Signalling Audio System:
    - Signalling Audio System: audiosystem/index.md
    #- Todo: audiosystem/Pages/todo.md
    - Namespaces: audiosystem/Namespaces/index.md